name: 'vscode-webdriverio Setup Workspace'
description: 'Sets up Node.js environment with PNPM for CI/CD workflows'
inputs:
  node-version:
    description: 'Node.js version to use (e.g., "20")'
    required: true

runs:
  using: composite
  steps:
    - name: 🧰 Setup PNPM
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        run_install: false

    - name: 🛠️ Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: ⚙️ Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: 🔧 Configure Git identity
      shell: bash
      run: |
        git config --global user.email "bot@webdriver.io"
        git config --global user.name "WebdriverIO Release Bot"
