version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    ignore:
      # updates to Node.js requires update to .nvmrc
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
    groups:
      patch-deps-updates-main:
        update-types:
          - 'patch'
      minor-deps-updates-main:
        update-types:
          - 'minor'
      major-deps-updates-main:
        update-types:
          - 'major'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
    open-pull-requests-limit: 10
    groups:
      patch-deps-updates:
        update-types:
          - 'patch'
      minor-deps-updates:
        update-types:
          - 'minor'
      major-deps-updates:
        update-types:
          - 'major'
