name: Auto Close Issue

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  close-not-reproducible-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          repo-token: ${{ secrets.WDIO_BOT_GITHUB_TOKEN }}
          only-issue-labels: 'Reproducible Example Missing'
          stale-issue-label: 'Stale :classical_building:'
          days-before-close: 0
          days-before-stale: 7
          close-issue-message: >
            Thanks for raising this issue 🙏

            Unfortunately, we are closing the issue as no reproducible samples were provided within 7 days.
            If there are any updates, please reopen this issue or create new one.

            If you have any questions please reach out to us on our [Discord](https://discord.webdriver.io/)
            channel. We are happy to help you out there.
