name: E2E tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      compatibility-mode:
        description: 'If “yes”, run test for compatibility with vscode'
        default: 'no'
        type: string

env:
  TURBO_TELEMETRY_DISABLED: 1
  VSCODE_WDIO_E2E_COMPATIBILITY_MODE: ${{ inputs.compatibility-mode }}
  FORCE_COLOR: 1

jobs:
  e2e:
    name: E2E Tests - ${{ matrix.scenario }} (${{ matrix.os }}.${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        scenario: ['basic', 'workspace']
    runs-on: ${{ matrix.os }}
    steps:
      - name: 👷 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: 🛠️ Setup workspace
        uses: ./.github/actions/setup-workspace
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⬇️ Download Build Archive
        uses: ./.github/actions/download-archive
        with:
          name: vscode-webdriverio
          path: .
          filename: vscode-webdriverio-build.zip

      - name: 🗃️ Use cached vscode
        uses: ./.github/actions/cache-vscode
        with:
          path: e2e/.wdio-vscode-service

      - name: 🖥️ Set screen resolution
        uses: ./.github/actions/set-screen-resolution

      - name: 🧪 Run the e2e test
        env:
          E2E_SCENARIO: ${{ matrix.scenario }}
        run: pnpm --filter @vscode-wdio/e2e run "test:e2e:${E2E_SCENARIO}"
        shell: bash

      - name: 📦 Upload Test Logs on Failure
        uses: ./.github/actions/upload-archive
        if: failure()
        with:
          name: ${{ inputs.compatibility-mode == 'yes' && 'compatibility' || 'e2e' }}-${{ matrix.scenario }}-logs-${{ matrix.os }}
          output: ${{ inputs.compatibility-mode == 'yes' && 'compatibility' || 'e2e' }}-${{ matrix.scenario }}-logs-${{ matrix.os }}.zip
          paths: e2e/logs

      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@ec99599aefe0bf96d14491e1d5f7e80d30e22247 # v1.1.0
        if: failure()
        with:
          timeout: '180000'
