name: CI

on:
  push:
    branches:
      - main
      - v[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci-build.yml
    with:
      os: 'ubuntu-latest'

  lint:
    name: Static code analysis
    uses: ./.github/workflows/ci-lint.yml

  typecheck:
    name: Typecheck
    needs: [lint, build]
    uses: ./.github/workflows/ci-typecheck.yml

  license-check:
    name: License Check
    needs: [lint, build]
    uses: ./.github/workflows/ci-license.yml

  unit:
    name: Unit
    needs: [lint, build]
    uses: ./.github/workflows/ci-unit.yml

  e2e:
    name: E2E
    needs: [lint, build]
    uses: ./.github/workflows/ci-e2e.yml

  compatibility:
    name: Compatibility
    needs: [lint, build]
    uses: ./.github/workflows/ci-e2e.yml
    with:
      compatibility-mode: 'yes'

  smoke-config:
    name: Smoke - Update Config
    needs: [lint, build, unit, license-check, typecheck, e2e]
    uses: ./.github/workflows/ci-smoke.yml
    with:
      scenario: 'config'

  smoke-timeout:
    name: Smoke - Worker idle timeout
    needs: [lint, build, unit, license-check, typecheck, e2e]
    uses: ./.github/workflows/ci-smoke.yml
    with:
      scenario: 'timeout'

  smoke-env:
    name: Smoke - Load .env files
    needs: [lint, build, unit, license-check, typecheck, e2e]
    uses: ./.github/workflows/ci-smoke.yml
    with:
      scenario: 'env'

  smoke-retro-wdio:
    name: Smoke - Run test with temporary configuration file when lower version of WDIO
    needs: [lint, build, unit, license-check, typecheck, e2e]
    uses: ./.github/workflows/ci-smoke.yml
    with:
      os: "['windows-latest']"
      scenario: 'retro-wdio-win'
