name: CI

on:
  push:
    branches:
      - main
      - v[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci-build.yml
    with:
      os: 'ubuntu-latest'

  lint:
    name: Static code analysis
    uses: ./.github/workflows/ci-lint.yml

  typecheck:
    name: Typecheck
    needs: [lint, build]
    uses: ./.github/workflows/ci-typecheck.yml

  unit:
    name: Unit
    needs: [lint, build]
    uses: ./.github/workflows/ci-unit.yml

  e2e:
    name: E2E
    needs: [lint, build]
    uses: ./.github/workflows/ci-e2e.yml

  compatibility:
    name: Compatibility
    needs: [lint, build]
    uses: ./.github/workflows/ci-e2e.yml
    with:
      compatibility-mode: 'yes'

  smoke:
    name: Smoke
    needs: [lint, build, e2e, compatibility]
    uses: ./.github/workflows/ci-smoke.yml
